from django.db import models
from django.utils import timezone

class Audit_csg_ctr_model(models.Model):
    id = models.AutoField(primary_key=True)
    N_CSG = models.CharField(max_length=2500)
    Constructeur_CSG = models.CharField(max_length=2500)
    Architecture = models.CharField(max_length=2500)
    Connexion = models.CharField(max_length=2500)
    Equipment_parent = models.CharField(max_length=2500)
    Equipement_Parent_BDR = models.CharField(max_length=2500)
    Delta_Equipement_parent = models.CharField(max_length=2500)
    Port_CSG = models.CharField(max_length=2500)
    Port_CSG_BDR = models.CharField(max_length=2500)
    Delta_Port_CSG = models.CharField(max_length=2500)
    Etat_port_CSG = models.CharField(max_length=2500)
    LAG_CSG = models.CharField(max_length=2500)
    LAG_CSG_BDR = models.CharField(max_length=2500)
    Delta_LAG_CSG = models.CharField(max_length=2500)
    Loopback0_CSG = models.CharField(max_length=2500)
    Loopback0_CSG_BDR = models.CharField(max_length=2500)
    Delta_Loopback0_CSG = models.CharField(max_length=2500)
    Loopback1_CSG = models.CharField(max_length=2500)
    Loopback1_CSG_BDR = models.CharField(max_length=2500)
    Delta_Loopback1_CSG = models.CharField(max_length=2500)
    IP_Interco_CSG = models.CharField(max_length=2500)
    IP_Interco_CSG_BDR = models.CharField(max_length=2500)
    Delta_IP_Interco_CSG = models.CharField(max_length=2500)
    Vlan_Interco_CSG = models.CharField(max_length=2500)
    VLAN_Interco_CSG_BDR = models.CharField(max_length=2500)
    Delta_Vlan_Trafic_CSG = models.CharField(max_length=2500)
    IP_SUP_CSG = models.CharField(max_length=2500)
    IP_Interco_SUP_CSG_BDR = models.CharField(max_length=2500)
    Delta_IP_Interco_SUP_CSG_BDR = models.CharField(max_length=2500)
    VLAN_SUP_CSG = models.CharField(max_length=2500)
    VLAN_Interco_SUP_CSG_BDR = models.CharField(max_length=2500)
    Delta_VLAN_Interco_SUP_CSG_BDR = models.CharField(max_length=2500)
    PORT_Parent = models.CharField(max_length=2500)
    PORT_CTR_BDR = models.CharField(max_length=2500)
    Delta_Port_CTR = models.CharField(max_length=2500)
    LAG_Parent = models.CharField(max_length=2500)
    Etat_Port_Parent = models.CharField(max_length=2500)
    LAG_CTR_BDR = models.CharField(max_length=2500)
    Delta_LAG_CTR = models.CharField(max_length=2500)
    IP_Interco_Parent = models.CharField(max_length=2500)
    IP_Interco_CTR_BDR = models.CharField(max_length=2500)
    Delta_IP_Interco_CTR_BDR = models.CharField(max_length=2500)
    Vlan_Interco_Parent = models.CharField(max_length=2500)
    VLAN_Interco_CTR_BDR = models.CharField(max_length=2500)
    Delta_VLAN_Interco_CTR_BDR = models.CharField(max_length=2500)
    IP_SUP_Parent = models.CharField(max_length=2500)
    IP_Interco_SUP_CTR_BDR = models.CharField(max_length=2500)
    Delta_IP_Interco_SUP_CTR_BDR = models.CharField(max_length=2500)
    VLAN_SUP_Parent = models.CharField(max_length=2500)
    VLAN_SUP_CTR_BDR = models.CharField(max_length=2500)
    Delta_VLAN_SUP_CTR_BDR = models.CharField(max_length=2500)
    IP_RADIO = models.CharField(max_length=2500)
    IP_Radio_BDR = models.CharField(max_length=2500)
    Delta_IP_Radio_BDR = models.CharField(max_length=2500)
    PORT_RADIO = models.CharField(max_length=2500)
    Port_Radio_BDR = models.CharField(max_length=2500)
    Delta_Port_Radio_BDR = models.CharField(max_length=2500)
    LAG_RADIO = models.CharField(max_length=2500)
    LAG_Radio_BDR = models.CharField(max_length=2500)
    Delta_LAG_Radio_BDR = models.CharField(max_length=2500)
    VLAN_RADIO = models.CharField(max_length=2500)
    VLAN_Radio_BDR = models.CharField(max_length=2500)
    Delta_VLAN_Radio_BDR = models.CharField(max_length=2500)
    ETAT_BDR_BDE = models.CharField(max_length=2500)
    Lien_IP_Interco = models.CharField(max_length=2500, null=True)
    Routage_Lien_IP = models.CharField(max_length=2500, null=True)
    Lien_IP_SUP = models.CharField(max_length=2500, null=True)
    Routage_Lien_IP_SUP = models.CharField(max_length=2500, null=True)
    Lien_AGG = models.CharField(max_length=2500, null=True)
    Routage_Lien_AGG = models.CharField(max_length=2500, null=True)
    Lien_PT = models.CharField(max_length=2500,null=True)
    Routage_Lien_PT = models.CharField(max_length=2500, null=True)
    Lien_ZT = models.CharField(max_length=2500,null=True)
    Routage_Lien_ZT = models.CharField(max_length=2500, null=True)
    Lien_ZT_CSG_FHT = models.CharField(max_length=2500, null=True)
    Lien_IP_Interco_CTR1 = models.CharField(max_length=2500, null=True)
    Routage_Lien_IP_CTR1 = models.CharField(max_length=2500, null=True)
    Lien_IP_SUP_CTR1 = models.CharField(max_length=2500, null=True)
    Routage_Lien_IP_SUP_CTR1 = models.CharField(max_length=2500, null=True)
    Lien_AGG_CTR1 = models.CharField(max_length=2500, null=True)
    Routage_Lien_AGG_CTR1 = models.CharField(max_length=2500, null=True)
    Lien_ZT_CTR1 = models.CharField(max_length=2500, null=True)
    Routage_Lien_ZT_CTR1 = models.CharField(max_length=2500, null=True)
    Lien_IP_INTERCO_CTR2 = models.CharField(max_length=2500, null=True)
    Routage_Lien_IP_INTERCO_CTR2 = models.CharField(max_length=2500, null=True)
    Lien_IP_SUP_CTR2 = models.CharField(max_length=2500, null=True)
    Routage_Lien_IP_INTERCO_SUP_CTR2 = models.CharField(max_length=2500, null=True)
    Lien_ZT_CTR2 = models.CharField(max_length=2500, null=True)
    Routage_Lien_ZT_CTR2 = models.CharField(max_length=2500, null=True)
    Lien_AGG_CTR2 = models.CharField(max_length=2500, null=True)
    Routage_Lien_AGG_CTR2 = models.CharField(max_length=2500, null=True)
    Lien_LO=models.CharField(max_length=2500, null=True)
    Lien_LO_CTR1 = models.CharField(max_length=2500, null=True)
    Lien_LO_CTR2 = models.CharField(max_length=2500, null=True)
    LAG = models.CharField(max_length=2500)
    VLAN = models.CharField(max_length=2500)
    Adresse_IP_Interco = models.CharField(max_length=2500)
    Adresse_IP_SUP = models.CharField(max_length=2500)
    Adresse_IP_Loopback0_1 = models.CharField(max_length=2500)
    Adresse_IP_Radio = models.CharField(max_length=2500)
    Modelisation_des_Liens = models.CharField(max_length=2500)
    Port = models.CharField(max_length=2500)
    Routage_des_Liens = models.CharField(max_length=2500)
    ETAT_CSG = models.CharField(max_length=2500)
    Date_column = models.DateField()
    Usine_Prod= models.CharField(max_length=2500, null=True)

    def __str__(self):
        return self.N_CSG

    class Meta:
        verbose_name = " Audit CSG CTR Model"
        verbose_name_plural = "Audit CSG CTR Models"

class AuditCSG(models.Model):
    n_csg = models.CharField(max_length=2500, null=True, blank=True)
    usine_prod = models.CharField(max_length=2500, null=True, blank=True)
    constructeur_csg = models.CharField(max_length=2500, null=True, blank=True)
    architecture = models.CharField(max_length=2500, null=True, blank=True)
    connexion = models.CharField(max_length=2500, null=True, blank=True)
    equipment_parent = models.CharField(max_length=2500, null=True, blank=True)
    equipement_parent_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_equipement_parent = models.CharField(max_length=2500, null=True, blank=True)
    port_csg = models.CharField(max_length=2500, null=True, blank=True)
    port_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_port_csg = models.CharField(max_length=2500, null=True, blank=True)
    etat_port_csg = models.CharField(max_length=2500, null=True, blank=True)
    lag_csg = models.CharField(max_length=2500, null=True, blank=True)
    lag_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_lag_csg = models.CharField(max_length=2500, null=True, blank=True)
    loopback0_csg = models.CharField(max_length=2500, null=True, blank=True)
    loopback0_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_loopback0_csg = models.CharField(max_length=2500, null=True, blank=True)
    loopback1_csg = models.CharField(max_length=2500, null=True, blank=True)
    loopback1_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_loopback1_csg = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_csg = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_ip_interco_csg = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_csg = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_vlan_trafic_csg = models.CharField(max_length=2500, null=True, blank=True)
    ip_sup_csg = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_sup_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_ip_interco_sup_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    vlan_sup_csg = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_sup_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_vlan_interco_sup_csg_bdr = models.CharField(max_length=2500, null=True, blank=True)
    port_parent = models.CharField(max_length=2500, null=True, blank=True)
    port_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_port_ctr = models.CharField(max_length=2500, null=True, blank=True)
    lag_parent = models.CharField(max_length=2500, null=True, blank=True)
    etat_port_parent = models.CharField(max_length=2500, null=True, blank=True)
    lag_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_lag_ctr = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_parent = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_ip_interco_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_parent = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_vlan_interco_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    ip_sup_parent = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_sup_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_ip_interco_sup_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    vlan_sup_parent = models.CharField(max_length=2500, null=True, blank=True)
    vlan_sup_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_vlan_sup_ctr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    ip_radio = models.CharField(max_length=2500, null=True, blank=True)
    ip_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_ip_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    port_radio = models.CharField(max_length=2500, null=True, blank=True)
    port_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_port_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    lag_radio = models.CharField(max_length=2500, null=True, blank=True)
    lag_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_lag_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    vlan_radio = models.CharField(max_length=2500, null=True, blank=True)
    vlan_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_vlan_radio_bdr = models.CharField(max_length=2500, null=True, blank=True)
    etat_bdr_bde = models.CharField(max_length=2500, null=True, blank=True)
    lien_ip_interco_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_ip_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    lien_ip_sup_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_ip_sup_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    lien_agg_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_agg_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    lien_zt_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_zt_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    lien_ip_interco_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_ip_interco_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    lien_ip_sup_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_ip_interco_sup_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    lien_zt_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_zt_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    lien_agg_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    routage_lien_agg_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    lien_lo_ctr1 = models.CharField(max_length=2500, null=True, blank=True)
    lien_lo_ctr2 = models.CharField(max_length=2500, null=True, blank=True)
    lag = models.CharField(max_length=2500, null=True, blank=True)
    lag_global = models.CharField(max_length=2500, null=True, blank=True)
    vlan = models.CharField(max_length=2500, null=True, blank=True)
    vlan_global = models.CharField(max_length=2500, null=True, blank=True)
    adresse_ip_interco = models.CharField(max_length=2500, null=True, blank=True)
    adresse_ip_sup = models.CharField(max_length=2500, null=True, blank=True)
    adresse_ip_loopback0_1 = models.CharField(max_length=2500, null=True, blank=True)
    adresse_ip_radio = models.CharField(max_length=2500, null=True, blank=True)
    modelisation_des_liens = models.CharField(max_length=2500, null=True, blank=True)
    port_csg_ctr = models.CharField(max_length=2500, null=True, blank=True)
    port_global = models.CharField(max_length=2500, null=True, blank=True)
    routage_des_liens = models.CharField(max_length=2500, null=True, blank=True)
    etat_de_coherence_imes = models.CharField(max_length=2500, null=True, blank=True)
    etat_de_coherence_radio = models.CharField(max_length=2500, null=True, blank=True)
    etat_csg_globale = models.CharField(max_length=2500, null=True, blank=True)
    insertion_date = models.DateField(max_length=2500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.n_csg or "Unnamed CSG"

    class Meta:
        db_table = 'audit_csg'

class Audit_ip_fh_model(models.Model):
    region = models.CharField(max_length=500)
    id_lien = models.CharField(max_length=500)
    equipement = models.CharField(max_length=500)
    site_geo = models.CharField(max_length=500)
    site_theo = models.CharField(max_length=500)
    region_1 = models.CharField(max_length=500)
    installe = models.CharField(max_length=500)
    type_extremite = models.CharField(max_length=500)
    adresse_ip = models.CharField(max_length=500, null=True, blank=True)
    statut_ip = models.CharField(max_length=500)
    constructeur = models.CharField(max_length=500)
    materiel = models.CharField(max_length=500)
    etat = models.CharField(max_length=500)
    nature = models.CharField(max_length=500)
    statut = models.CharField(max_length=500)
    statut_lp35 = models.CharField(max_length=500)
    statut_swap_fh = models.CharField(max_length=500)
    ip_omc = models.CharField(max_length=500, null=True, blank=True)  
    tdj_osa = models.CharField(max_length=500)
    check_ip = models.CharField(max_length=500)
    tdj_cdr = models.CharField(max_length=500)
    tdj_swap_ip = models.CharField(max_length=500)
    date_demande_swap_dci = models.DateField(null=True, blank=True)
    nb_fht = models.IntegerField()
    statut_coherence_adresses_ip = models.CharField(max_length=500)
    porteur = models.CharField(max_length=500)
    action_description = models.CharField(max_length=500)
    type_incoherence = models.CharField(max_length=500,blank=True)
    Data_Insertion_Date = models.DateField()

    def __str__(self):
        return f"{self.id_lien} - {self.equipement}"
    class Meta:
        verbose_name = "Audit IP FH Model"
        verbose_name_plural = "Audit IP FH Models"

class AuditATR(models.Model):
    key = models.CharField(max_length=2500, null=True, blank=True)
    atr = models.CharField(max_length=2500, null=True, blank=True)
    connexion = models.CharField(max_length=2500, null=True, blank=True)
    equipment_parent = models.CharField(max_length=2500, null=True, blank=True)
    equipement_parent_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_equipement_parent = models.CharField(max_length=2500, null=True, blank=True)
    port_atr = models.CharField(max_length=2500, null=True, blank=True)
    port_atr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_port_atr = models.CharField(max_length=2500, null=True, blank=True)
    lag_atr = models.CharField(max_length=2500, null=True, blank=True)
    lag_atr_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_lag_atr = models.CharField(max_length=2500, null=True, blank=True)
    loopback0_atr = models.CharField(max_length=2500, null=True, blank=True)
    lo_ip = models.CharField(max_length=2500, null=True, blank=True)
    delta_loopback0_atr = models.CharField(max_length=2500, null=True, blank=True)
    loopback1_atr = models.CharField(max_length=2500, null=True, blank=True)
    l1_ip = models.CharField(max_length=2500, null=True, blank=True)
    delta_loopback1_atr = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_atr = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_ip_interco_atr = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_vlan_interco_atr = models.CharField(max_length=2500, null=True, blank=True)
    port_parent = models.CharField(max_length=2500, null=True, blank=True)
    port_parent_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_port_parent = models.CharField(max_length=2500, null=True, blank=True)
    lag_parent = models.CharField(max_length=2500, null=True, blank=True)
    lag_parent_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_lag_parent = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_parent = models.CharField(max_length=2500, null=True, blank=True)
    ip_interco_parent_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_ip_interco_parent = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_parent = models.CharField(max_length=2500, null=True, blank=True)
    vlan_interco_parent_bdr = models.CharField(max_length=2500, null=True, blank=True)
    delta_vlan_interco_parent = models.CharField(max_length=2500, null=True, blank=True)
    port = models.CharField(max_length=2500, null=True, blank=True)
    lag = models.CharField(max_length=2500, null=True, blank=True)
    vlan = models.CharField(max_length=2500, null=True, blank=True)
    addresse_ip = models.CharField(max_length=2500, null=True, blank=True)
    etat_parent = models.CharField(max_length=2500, null=True, blank=True)
    etat_des_couples = models.CharField(max_length=2500, null=True, blank=True)
    etat_final = models.CharField(max_length=2500, null=True, blank=True)
    etat_gcr = models.CharField(max_length=2500, null=True, blank=True)
    service = models.CharField(max_length=2500, null=True, blank=True)
    responsable = models.CharField(max_length=2500, null=True, blank=True)
    insertion_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.atr or "Unnamed ATR"

    class Meta:
        db_table = 'audit_atr'
        verbose_name = "Audit ATR"
        verbose_name_plural = "Audit ATRs"





class AuditDoublonsIP(models.Model):
    doublons_adresse_ip = models.CharField(max_length=2500, null=True, blank=True)
    add_ip_paire = models.CharField(max_length=2500, null=True, blank=True)
    add_ip_impaire = models.CharField(max_length=2500, null=True, blank=True)
    equipment_radio_dans_bdr_trans = models.CharField(max_length=2500, null=True, blank=True)
    equipment_trans_dans_bdr_trans = models.CharField(max_length=2500, null=True, blank=True)
    equipment_radio_dans_bde_trans = models.CharField(max_length=2500, null=True, blank=True)
    equipment_trans_dans_bde_trans = models.CharField(max_length=2500, null=True, blank=True)
    equipment_radio_dans_bde_radio = models.CharField(max_length=2500, null=True, blank=True)
    port_dans_bde_trans = models.CharField(max_length=2500, null=True, blank=True)
    existe_dans_bdr_trans = models.CharField(max_length=2500, null=True, blank=True)
    doublons_dans_bde_trans = models.CharField(max_length=2500, null=True, blank=True)
    doublons_dans_bde_radio = models.CharField(max_length=2500, null=True, blank=True)
    insertion_date = models.DateField(null=False, blank=False)


    class Meta:
        db_table = 'audit_doublons_ip'



class CustomAudit(models.Model):
    # Define the choices for audit type using Django's models.TextChoices
    class AuditType(models.TextChoices):
        CATALOGUE = 'CAT'
        CONTROLLE = 'CONT'

    title = models.CharField(max_length=2500, null=False, blank=False)
    image = models.ImageField(upload_to='audit_images/', null=False, blank=False)
    audit_type = models.CharField(
        max_length=5,
        choices=AuditType.choices,
        null=False,
        blank=False,
    )

    def __str__(self):
        return self.title