# Generated by Django 3.2.21 on 2024-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20231025_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_ZT',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_ZT',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Lien_PT',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Lien_ZT_CSG_FHT',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_PT',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
