# Generated by Django 3.2.21 on 2024-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20240109_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_AGG_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_AGG_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_IP_INTERCO_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_IP_Interco_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_IP_SUP_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_IP_SUP_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_ZT_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_ZT_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_AGG_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_AGG_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_IP_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_IP_INTERCO_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_IP_SUP_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_IP_SUP_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_ZT_CTR1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_ZT_CTR2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
