# Generated by Django 3.2.21 on 2024-01-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auto_20240118_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit_csg_ctr_model',
            old_name='Routage_Lien_IP_SUP_CTR2',
            new_name='Routage_Lien_IP_INTERCO_SUP_CTR2',
        ),
    ]
