# Generated by Django 3.2.21 on 2024-01-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_rename_routage_lien_ip_sup_ctr2_audit_csg_ctr_model_routage_lien_ip_interco_sup_ctr2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Lien_IP_Interco',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
