# Generated by Django 3.2.21 on 2024-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_alter_audit_csg_ctr_model_lien_ip_interco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Lien_AGG',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Lien_IP_SUP',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_AGG',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_IP',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audit_csg_ctr_model',
            name='Routage_Lien_IP_SUP',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
