# Generated by Django 3.0.5 on 2024-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_auto_20240123_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_ip_fh_model',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
