# Generated by Django 3.2.21 on 2024-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_auto_20240227_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_ip_fh_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
