# Generated by Django 3.2.21 on 2024-05-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0012_alter_audit_ip_fh_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_ip_fh_model',
            name='Type_incoherence',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
