# Generated by Django 3.2.21 on 2024-05-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0013_audit_ip_fh_model_type_incoherence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit_ip_fh_model',
            old_name='Type_incoherence',
            new_name='type_incoherence',
        ),
    ]
