# Generated by Django 3.2.21 on 2024-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0014_rename_type_incoherence_audit_ip_fh_model_type_incoherence'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_LO_CTR1',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_LO_CTR2',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
