# Generated by Django 3.2.21 on 2024-08-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0015_auto_20240722_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Lien_LO',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
