# Generated by Django 3.2.21 on 2024-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0016_audit_csg_ctr_model_lien_lo'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_csg_ctr_model',
            name='Usine_Prod',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
