# Generated by Django 3.2.21 on 2025-01-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0018_auditcsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcsg',
            name='adresse_ip_interco',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='adresse_ip_loopback0_1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='adresse_ip_radio',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='adresse_ip_sup',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='architecture',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='connexion',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='constructeur_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_equipement_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_ip_interco_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_ip_interco_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_ip_interco_sup_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_ip_interco_sup_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_ip_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_lag_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_lag_ctr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_lag_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_loopback0_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_loopback1_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_port_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_port_ctr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_port_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_vlan_interco_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_vlan_interco_sup_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_vlan_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_vlan_sup_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='delta_vlan_trafic_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='equipement_parent_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='equipment_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='etat_bdr_bde',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='etat_csg_globale',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='etat_de_coherence_imes',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='etat_de_coherence_radio',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='etat_port_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='etat_port_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_interco_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_interco_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_interco_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_interco_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_interco_sup_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_interco_sup_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_radio',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_sup_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='ip_sup_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag_global',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag_radio',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lag_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_agg_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_agg_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_ip_interco_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_ip_interco_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_ip_sup_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_ip_sup_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_lo_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_lo_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_zt_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='lien_zt_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='loopback0_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='loopback0_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='loopback1_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='loopback1_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='modelisation_des_liens',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='n_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_csg_ctr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_global',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_radio',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='port_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_des_liens',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_agg_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_agg_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_ip_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_ip_interco_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_ip_interco_sup_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_ip_sup_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_zt_ctr1',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='routage_lien_zt_ctr2',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='usine_prod',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_global',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_interco_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_interco_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_interco_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_interco_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_interco_sup_csg_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_radio',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_radio_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_sup_csg',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_sup_ctr_bdr',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='auditcsg',
            name='vlan_sup_parent',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
