# Generated by Django 3.2.21 on 2025-01-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0019_auto_20250106_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcsg',
            name='insertion_date',
            field=models.DateField(blank=True, max_length=2500, null=True),
        ),
    ]
