# Generated by Django 3.2.21 on 2024-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluxoa',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID_CELL', models.CharField(max_length=255)),
                ('ETAT_EXPLOITATION_CRS', models.CharField(max_length=255)),
                ('PRESENCE', models.CharField(max_length=255)),
                ('STATUS', models.CharField(max_length=255)),
                ('PRESENCE_TABLE', models.CharField(max_length=255)),
                ('DATE', models.DateField()),
            ],
        ),
    ]
