# Generated by Django 3.2.21 on 2024-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_radio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellDataDci',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cell_State_BDE', models.CharField(max_length=500)),
                ('Cell_State_BDR', models.CharField(max_length=500)),
                ('CellState_Commentaire', models.CharField(max_length=500)),
                ('CellName', models.CharField(max_length=500)),
                ('CODE_ACQUITTEMENT', models.CharField(max_length=500)),
                ('CODE_FICHIER', models.CharField(max_length=500)),
                ('Constructeur', models.CharField(max_length=500)),
                ('ETAT_EXPLOITATION_CRS', models.CharField(max_length=500)),
                ('ETAT_EXPLOITATION_CRS_R', models.CharField(max_length=500)),
                ('CELLNAME_BDE', models.CharField(max_length=500)),
                ('ID_CELL', models.CharField(max_length=500)),
                ('ID_CELL_cible', models.CharField(max_length=500)),
                ('PRESENCE', models.CharField(max_length=500)),
                ('NOM_FICHIER', models.CharField(max_length=500)),
                ('Site_Logique', models.CharField(max_length=500)),
                ('TECHNO', models.CharField(max_length=500)),
                ('Site_Theorique', models.CharField(max_length=500)),
                ('TYPE_OBJET', models.CharField(max_length=500)),
                ('ZONE_NOK', models.CharField(max_length=500)),
                ('DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CellDataSfr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=500)),
                ('CODE_FICHIER', models.CharField(max_length=500)),
                ('IDcell', models.CharField(max_length=500)),
                ('NOM_FICHIER', models.CharField(max_length=500)),
                ('ID_CELL_cible', models.CharField(max_length=500)),
                ('TYPE_OBJET', models.CharField(max_length=500)),
                ('TECHNO', models.CharField(max_length=500)),
                ('ZONE_NOK', models.CharField(max_length=500)),
            ],
        ),
    ]
