# Generated by Django 3.2.21 on 2024-04-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_radio', '0002_celldatadci_celldatasfr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celldatadci',
            name='DATE',
        ),
    ]
