from django.db import models
from django.contrib.auth.models import User  # Import the User model

class L712CasRadio(models.Model):
    id = models.AutoField(primary_key=True)
    equipement_a = models.CharField(max_length=255, null=True, blank=True)
    element_conf = models.CharField(max_length=255, null=True, blank=True)
    responsable = models.CharField(max_length=255, null=True, blank=True)
    phase_audit = models.CharField(max_length=255, null=True, blank=True)
    num_changement_parent = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_ip = models.CharField(max_length=255, null=True, blank=True)
    etat = models.CharField(max_length=255, null=True, blank=True)
    statut = models.CharField(max_length=255, null=True, blank=True)
    site_geo_a = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a = models.CharField(max_length=255, null=True, blank=True)
    constructeur_a = models.CharField(max_length=255, null=True, blank=True)
    adresse_ip_a = models.CharField(max_length=255, null=True, blank=True)
    equipement_b = models.CharField(max_length=255, null=True, blank=True)
    site_geo_b = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b = models.CharField(max_length=255, null=True, blank=True)
    constructeur_b = models.CharField(max_length=255, null=True, blank=True)
    nom_interface_a = models.CharField(max_length=255, null=True, blank=True)
    nom_interface_b = models.CharField(max_length=255, null=True, blank=True)
    adresse_ip_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_ip = models.CharField(max_length=255, null=True, blank=True)
    vlan_a = models.CharField(max_length=255, null=True, blank=True)
    vlan_b = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_ip = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_pt = models.CharField(max_length=255, null=True, blank=True)
    etat_pt = models.CharField(max_length=255, null=True, blank=True)
    statut_pt = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_pt = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a_pt = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_pt = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b_pt = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_pt = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_pt = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_agg = models.CharField(max_length=255, null=True, blank=True)
    etat_agg = models.CharField(max_length=255, null=True, blank=True)
    statut_agg = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_agg = models.CharField(max_length=255, null=True, blank=True)
    num_lag_a = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_agg = models.CharField(max_length=255, null=True, blank=True)
    num_lag_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_agg = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_agg = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_zt_client = models.CharField(max_length=255, null=True, blank=True)
    etat_zt_client = models.CharField(max_length=255, null=True, blank=True)
    statut_zt_client = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_zt_client = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a_zt_client = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_zt_client = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b_zt_client = models.CharField(max_length=255, null=True, blank=True)
    lien_transmission_tous = models.CharField(max_length=255, null=True, blank=True)
    liste_transmission = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    etat_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    statut_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    ip = models.CharField(max_length=255, null=True, blank=True)
    adresse_ip_bde = models.CharField(max_length=255, null=True, blank=True)
    vlan_bde = models.CharField(max_length=255, null=True, blank=True)
    port_bde = models.CharField(max_length=255, null=True, blank=True)
    interface_bde = models.CharField(max_length=255, null=True, blank=True)
    porteur_bde = models.CharField(max_length=255, null=True, blank=True)
    radio_bde = models.CharField(max_length=255, null=True, blank=True)
    router_bde = models.CharField(max_length=255, null=True, blank=True)
    statut_arp = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_zt_client = models.CharField(max_length=255, null=True, blank=True)
    nombre_ip_present = models.CharField(max_length=255,null=True, blank=True)
    nombre_ip_requis = models.CharField(max_length=255,null=True, blank=True)
    delta_nombre_ip_existants = models.CharField(max_length=255,null=True, blank=True)
    routage_radio = models.CharField(max_length=255, null=True, blank=True)
    delta_vlan = models.CharField(max_length=255,null=True, blank=True)
    delta_equipement_lien_ip_pt = models.CharField(max_length=255,null=True, blank=True)
    delta_port_agg_fht = models.CharField(max_length=255,null=True, blank=True)
    delta_fht_lien_agg_zt = models.CharField(max_length=255,null=True, blank=True)
    conformite_status = models.CharField(max_length=255, null=True, blank=True)
    conformite_regles_choix_lag = models.CharField(max_length=255, null=True, blank=True)
    conformite_regles_choix_port = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_extremite_a = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_extremite_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_vlan = models.CharField(max_length=255, null=True, blank=True)
    statut_coherence = models.CharField(max_length=255, null=True, blank=True)
    nb_incoherences = models.CharField(max_length=255,null=True, blank=True)
    statut_incoherence = models.CharField(max_length=255, null=True, blank=True)
    insertion_date = models.DateField(max_length=2500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = "l71_2_cas_radio"

class L712CasCsg(models.Model):
    id = models.AutoField(primary_key=True)
    csg_pendulaire = models.CharField(max_length=255, null=True, blank=True)
    gcr_a = models.CharField(max_length=255, null=True, blank=True)
    gcr_b = models.CharField(max_length=255, null=True, blank=True)
    appartenance_lp = models.CharField(max_length=255, null=True, blank=True)
    responsable = models.CharField(max_length=255, null=True, blank=True)
    phase_audit = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_ip = models.CharField(max_length=255, null=True, blank=True)
    equipement_a = models.CharField(max_length=255, null=True, blank=True)
    etat = models.CharField(max_length=255, null=True, blank=True)
    statut = models.CharField(max_length=255, null=True, blank=True)
    site_geo_a = models.CharField(max_length=255, null=True, blank=True)
    lag_a_bde = models.CharField(max_length=255, null=True, blank=True)
    num_lag_a = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a = models.CharField(max_length=255, null=True, blank=True)
    constructeur_a = models.CharField(max_length=255, null=True, blank=True)
    parent_bde = models.CharField(max_length=255, null=True, blank=True)
    equipement_b = models.CharField(max_length=255, null=True, blank=True)
    site_geo_b = models.CharField(max_length=255, null=True, blank=True)
    lag_b_bde = models.CharField(max_length=255, null=True, blank=True)
    num_lag_b = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b = models.CharField(max_length=255, null=True, blank=True)
    constructeur_b = models.CharField(max_length=255, null=True, blank=True)
    nom_interface_a = models.CharField(max_length=255, null=True, blank=True)
    vlan_a_bde = models.CharField(max_length=255, null=True, blank=True)
    vlan_a = models.CharField(max_length=255, null=True, blank=True)
    adresse_ip_a_bde = models.CharField(max_length=255, null=True, blank=True)
    adresse_ip_a = models.CharField(max_length=255, null=True, blank=True)
    nom_interface_b = models.CharField(max_length=255, null=True, blank=True)
    adresse_ip_b_bde = models.CharField(max_length=255, null=True, blank=True)
    vlan_b_bde = models.CharField(max_length=255, null=True, blank=True)
    vlan_b = models.CharField(max_length=255, null=True, blank=True)
    adresse_ip_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_ip = models.CharField(max_length=255, null=True, blank=True)
    lien_agg = models.CharField(max_length=255, null=True, blank=True)
    etat_agg = models.CharField(max_length=255, null=True, blank=True)
    statut_agg = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_agg = models.CharField(max_length=255, null=True, blank=True)
    num_lag_a_agg = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_agg = models.CharField(max_length=255, null=True, blank=True)
    num_lag_b_agg = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_agg = models.CharField(max_length=255, null=True, blank=True)
    lien_pt = models.CharField(max_length=255, null=True, blank=True)
    etat_pt = models.CharField(max_length=255, null=True, blank=True)
    statut_pt = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_pt = models.CharField(max_length=255, null=True, blank=True)
    port_a_bde_pt = models.CharField(max_length=255, null=True, blank=True)
    num_port_a_pt = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a_pt = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_pt = models.CharField(max_length=255, null=True, blank=True)
    port_b_bde_pt = models.CharField(max_length=255, null=True, blank=True)
    num_port_b_pt = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b_pt = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_pt = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_zt_client = models.CharField(max_length=255, null=True, blank=True)
    etat_zt_client = models.CharField(max_length=255, null=True, blank=True)
    statut_zt_client = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_zt_client = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a_zt_client = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_zt_client = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b_zt_client = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_zt_client = models.CharField(max_length=255, null=True, blank=True)
    nom_lien_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    etat_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    statut_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    equipement_a_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    nom_port_a_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    equipement_b_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    nom_port_b_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    coherence_routage_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_ip = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_agg = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_pt = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_zt_client = models.CharField(max_length=255, null=True, blank=True)
    routage_lien_zt_reseau = models.CharField(max_length=255, null=True, blank=True)
    nombre_ip_present = models.CharField(max_length=255, null=True, blank=True)
    nombre_ip_requis = models.CharField(max_length=255, null=True, blank=True)
    delta_nombre_ip_existants = models.CharField(max_length=255, null=True, blank=True)
    routage = models.CharField(max_length=255, null=True, blank=True)
    delta_vlan = models.CharField(max_length=255, null=True, blank=True)
    delta_equipement_lien_ip_pt = models.CharField(max_length=255, null=True, blank=True)
    conformite_status = models.CharField(max_length=255, null=True, blank=True)
    conformite_lag_dl = models.CharField(max_length=255, null=True, blank=True)
    conformite_port_dl = models.CharField(max_length=255, null=True, blank=True)
    conformite_lag_ul = models.CharField(max_length=255, null=True, blank=True)
    conformite_port_ul = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_adrs_ip_a = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_port_a = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_lag_a = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_vlan_a = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_extremite_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_adrs_ip_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_port_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_lag_b = models.CharField(max_length=255, null=True, blank=True)
    coherence_bdr_bde_vlan_b = models.CharField(max_length=255, null=True, blank=True)
    statut_coherence = models.CharField(max_length=255, null=True, blank=True)
    nb_incoherences = models.CharField(max_length=255, null=True, blank=True)
    etat_de_coherence_bdr = models.CharField(max_length=255, null=True, blank=True)
    etat_de_coherence_bdr_bde = models.CharField(max_length=255, null=True, blank=True)
    etat_de_coherence_equipment = models.CharField(max_length=255, null=True, blank=True)

    insertion_date = models.DateField(max_length=2500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = "l71_2_cas_csg"
