# Generated by Django 3.2.21 on 2024-12-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_qualite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l712casradio',
            name='delta_equipement_lien_ip_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='l712casradio',
            name='delta_fht_lien_agg_zt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='l712casradio',
            name='delta_nombre_ip_existants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='l712casradio',
            name='delta_port_agg_fht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='l712casradio',
            name='delta_vlan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='l712casradio',
            name='nb_incoherences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='l712casradio',
            name='nombre_ip_present',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='l712casradio',
            name='nombre_ip_requis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
