# Generated by Django 3.2.21 on 2024-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_qualite', '0003_auto_20241204_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='l712casradio',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
