# Generated by Django 3.2.21 on 2024-12-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_qualite', '0005_l712cascsg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='l712cascsg',
            old_name='statut_de_coherence',
            new_name='statut_coherence',
        ),
    ]
